In [28]:
import torch

In [29]:
def activation(x):
    #signoid function of "x" tensor
    return 1/(1+torch.exp(-x))

In [30]:
torch.manual_seed(7)

features = torch.randn((1,5))

weight = torch.rand_like(features)

In [31]:
print(features.shape)
print(features)

torch.Size([1, 5])
tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])


In [32]:
print(weight.shape)
print(weight)

torch.Size([1, 5])
tensor([[0.2868, 0.2063, 0.4451, 0.3593, 0.7204]])


In [33]:
bias = torch.randn((1,1))
print(bias)

tensor([[-0.8948]])


In [34]:
#calculate the output of this nn
y = activation(torch.mm(features, weight.view(5,1)) + bias)
print(y)

tensor([[0.6140]])
